### PR TITLE
Add clipboard upload

### PR DESCRIPTION
**Pull request by TicClick**

### CODE REVIEW

**Comment by sunmockyang** [comment]
wow this looks awfully clean and tempting.... I actually haven't used puush in a bit but do you know what happens if you have an image in your clipboard? I'm wondering if puush on osx/windows attaches file extensions to the file name depending if you have text or an image

**Comment by TicClickie** [comment]
I've tested it by piping an image file to `xclip`, but it doesn't seem to be working with images copied from, say, browsers and such. I'll come up with something soon to fix that.

As for OS X / Windows, yes, it does append extension to the URL, but it seems we can neglect that, because it can be accessed even without one; see http://puu.sh/nAjQJ/d7d9820470 and even http://puu.sh/nAjQJ/d7d9820470fdjofdsjksdfasdffsdsdaf: it works as long as the prefix is correct.

**Comment by TicClickie** [comment]
Done! c2ddcd7 should be it.

**Comment by sunmockyang** [comment]
Hey, sorry for not getting back to this for so long. I think the in the case of not being able to determine the mime type, we should append text at the start of the text before we puush with a message to inform the user what might've happened. I think what I'll do it merge this and then add that message myself. Good stuff, and thanks for contributing.

**Pull request merged**
